language: php

php:
  - 7.3.1

before_script:
  - cp .env.travis .env
  - mysql -e 'create database testing_db;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate
  - php artisan db:seed
  - php artisan key:generate

script:
  - vendor/bin/phpunit

deploy:
  provider: heroku
  api_key:
    secure: "63d7ab61-e329-4566-9557-6593f1bc1e93"
  app: "albertlaravel"
  on:
    all_branches: develop